name: Auto_Update_Nodes
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch: # 允许手动点击运行
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # 显式声明写入权限
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests
      - run: python fetch.py
      - name: Push updates
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add sub.txt
          git commit -m "Filter dead nodes" || exit 0
          git push
